# config.yaml

save_data: eng-ata/run/data
src_vocab: eng-ata/run/vocab.src
tgt_vocab: eng-ata/run/vocab.tgt

src_subword_model: eng-ata/run/spm.model
tgt_subword_model: eng-ata/run/spm.model
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece

data:
  corpus_1:
    path_src: eng-ata/src-train.spm.txt
    path_tgt: eng-ata/tgt-train.spm.txt
  valid:
    path_src: eng-ata/src-val.spm.txt
    path_tgt: eng-ata/tgt-val.spm.txt

world_size: 1
gpu_ranks: [0]

train_steps: 10000
valid_steps: 500
save_checkpoint_steps: 500
batch_size: 64

model_type: transformer
encoder_type: transformer
decoder_type: transformer
position_encoding: true
share_embeddings: true
optim: adam
adam_beta2: 0.998
decay_method: noam
warmup_steps: 4000
learning_rate: 2.0
max_grad_norm: 0.0
param_init: 0
param_init_glorot: true
label_smoothing: 0.1

log_file: train.log
tensorboard: true
tensorboard_log_dir: runs/
