save_model: toy-ende/run/model
save_checkpoint_steps: 1000
valid_steps: 200
train_steps: 8000
report_every: 50

# Batching
bucket_size: 262144
world_size: 1
gpu_ranks: [0]
num_workers: 4
batch_type: "tokens"
batch_size: 8192
valid_batch_size: 2048
accum_count: [2]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 1.5
warmup_steps: 4000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.2 # increased from 0.1
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 4 # reduced from 6
dec_layers: 4 # reduced from 6
heads: 8
hidden_size: 256 # reduced from 512
word_vec_size: 256
transformer_ff: 1024 # reduced from 2048
dropout: [0.3] # increased from 0.1
attention_dropout: [0.3] # increased from 0.1

# Data paths
save_data: toy-ende/run/example
src_vocab: toy-ende/run/example.vocab.src
tgt_vocab: toy-ende/run/example.vocab.tgt

# Corpus
data:
  corpus_1:
    path_src: toy-ende/src-train.txt
    path_tgt: toy-ende/tgt-train.txt
  valid:
    path_src: toy-ende/src-val.txt
    path_tgt: toy-ende/tgt-val.txt
