# Saving paths
save_model: eng-ata/run/model
save_checkpoint_steps: 1000
valid_steps: 500
train_steps: 15000
report_every: 50

# Hardware and batching
world_size: 1
gpu_ranks: [0]
bucket_size: 262144
num_workers: 4
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 1024
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 7.0 # You can try 0.7 if unstable
warmup_steps: 4000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init_glorot: true
normalization: "tokens"

# Model architecture
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 3
dec_layers: 3
heads: 8
hidden_size: 192
word_vec_size: 192
transformer_ff: 768

dropout: [0.4]
attention_dropout: [0.4]

# Data (with SentencePiece tokenized files)
save_data: eng-ata/run/example

src_vocab: eng-ata/run/example.vocab.src
tgt_vocab: eng-ata/run/example.vocab.tgt

data:
  corpus_1:
    path_src: eng-ata/src-train.spm.txt
    path_tgt: eng-ata/tgt-train.spm.txt
  valid:
    path_src: eng-ata/src-val.spm.txt
    path_tgt: eng-ata/tgt-val.spm.txt
